# Generated by Django 3.2 on 2021-04-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('text', models.TextField()),
                ('is_pub', models.BooleanField(default=False, verbose_name='is published?')),
                ('first_pub_at', models.DateTimeField(null=True, verbose_name='first published time')),
                ('pub_at', models.DateTimeField(null=True, verbose_name='last published time')),
                ('edited_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
