# Generated by Django 3.2 on 2021-04-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='first_pub_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='first published time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last published time'),
        ),
    ]
